language: java

jdk:
  - openjdk8
  - openjdk11

addons:
  sonarcloud:
    organization: jinahya-github
    token: ${SONAR_TOKEN}
    branches:
      - develop
      - master

script:
  - sonar-scanner